// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3UNmVe2wTXx0N1TU_cUWfdrTzczM1Bos',
    appId: '1:308390276763:web:90f562251505b7330d603e',
    messagingSenderId: '308390276763',
    projectId: 'train-ticket-booking-app-e1926',
    authDomain: 'train-ticket-booking-app-e1926.firebaseapp.com',
    storageBucket: 'train-ticket-booking-app-e1926.appspot.com',
    measurementId: 'G-48113BDWDH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrzRfO3lkuz727lw3AF7fRPzrUe9QyloY',
    appId: '1:308390276763:android:15a712b6fafaab4c0d603e',
    messagingSenderId: '308390276763',
    projectId: 'train-ticket-booking-app-e1926',
    storageBucket: 'train-ticket-booking-app-e1926.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsU2pISXQK2GexM8cqSJEOvYPWLj_jvfM',
    appId: '1:308390276763:ios:497b8c281c6411870d603e',
    messagingSenderId: '308390276763',
    projectId: 'train-ticket-booking-app-e1926',
    storageBucket: 'train-ticket-booking-app-e1926.appspot.com',
    iosBundleId: 'com.example.trainTicketBookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsU2pISXQK2GexM8cqSJEOvYPWLj_jvfM',
    appId: '1:308390276763:ios:497b8c281c6411870d603e',
    messagingSenderId: '308390276763',
    projectId: 'train-ticket-booking-app-e1926',
    storageBucket: 'train-ticket-booking-app-e1926.appspot.com',
    iosBundleId: 'com.example.trainTicketBookingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3UNmVe2wTXx0N1TU_cUWfdrTzczM1Bos',
    appId: '1:308390276763:web:ae3960297d03e2010d603e',
    messagingSenderId: '308390276763',
    projectId: 'train-ticket-booking-app-e1926',
    authDomain: 'train-ticket-booking-app-e1926.firebaseapp.com',
    storageBucket: 'train-ticket-booking-app-e1926.appspot.com',
    measurementId: 'G-F9VTCTSC5Q',
  );
}
